config/routes.rb
Rails.application.routes.draw do


  # User authentication routes
  devise_for :users
  devise_scope :user do
    get 'sign-in', :to => 'devise/sessions#new'
    get 'account-update', to: 'devise/registrations#edit'
    get 'create-account', to: 'devise/registrations#new'
  end


  # Routes for the silas lights
  resources :silas, only: [:index, :show, :create, :destroy]


  # Root to if logged in
  authenticated :user do
    root to: 'silas#index', as: :authenticated_root
  end

  root to: 'silas#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sila.rb
class Sila < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :all_sila_lights

  def all_sila_lights
    @silas = Sila.all
  end
end

app/controllers/silas_controller.rb
class SilasController < ApplicationController
  include SilasHelper

  require 'mechanize'
  before_action :set_sila, only: [:show, :edit, :update, :destroy]

  # GET /silas
  # GET /silas.json
  def index
    # Process lights from current customer (saves new ones, and returns a count)
    @lights_count = find_lights

    # All silas lights from the DB is retrived from application controller - sila_lights



  end

  # GET /silas/1
  # GET /silas/1.json
  def show
  end

  # GET /silas/new
  def new
    @sila = Sila.new
  end

  # GET /silas/1/edit
  def edit
  end

  # POST /silas
  # POST /silas.json
  def create
    @sila = Sila.new(sila_params)

    respond_to do |format|
      if @sila.save
        format.html { redirect_to @sila, notice: 'Sila was successfully created.' }
        format.json { render :show, status: :created, location: @sila }
      else
        format.html { render :new }
        format.json { render json: @sila.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /silas/1
  # PATCH/PUT /silas/1.json
  def update
    respond_to do |format|
      if @sila.update(sila_params)
        format.html { redirect_to @sila, notice: 'Sila was successfully updated.' }
        format.json { render :show, status: :ok, location: @sila }
      else
        format.html { render :edit }
        format.json { render json: @sila.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /silas/1
  # DELETE /silas/1.json
  def destroy
    @sila.destroy
    respond_to do |format|
      format.html { redirect_to silas_url, notice: 'Sila was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def temp_lights

    # Log into the portal
    mechanize = Mechanize.new
    page_full = mechanize.get('https://www.sila-signalbau.de/Login_Ampelueberwachung.htm?ActiveID=1226')
    form = page_full.form('form1')
    form['ctl01$tbUser'] = 'Drammen08'
    form['ctl01$tbPassword'] = 'Avdeling08'
    page = form.click_button

    # Search the page for all lights
    temp_list = page.search('tr td').map{ |x | x.text }
    lights_count = (temp_list.count / 11) - 1

    # Create an nested array for each light
    lights = Array.new

    # Add each light into appropriate array container
    temp_count = 1
    lights_count.times do
      lights << temp_list[(temp_count * 11)..((temp_count*11)+10)]
      temp_count += 1
    end

    return lights
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sila
      @sila = Sila.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sila_params
      params.require(:sila).permit(:sila_id, :ampel_id)
    end


    # find and maybe create lights from portal page
    def find_lights
      # Scrapes Sila-sinalbau.de for sila lights from the customer
      lights_from_page = helper_get_lights

      # Create lights that are not present in DB
      lights_from_page.each do |light|
        helper_create_lights_if_not_there(light)
      end

      # Return count of lights
      return lights_from_page.count
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def helper_flash_type(flash_type)
    case flash_type
    when "alert"
      return "alert"
    # Else is the standard Notice flash
    else
      return "notice"
    end
  end

end

app/helpers/sidebar_helper.rb
module SidebarHelper

  def helper_sidebar_menu(controller_name, action_name)

  end
end

app/helpers/silas_helper.rb
module SilasHelper

  # returns sila or ampel string and number
  def helper_sila_or_ampel_id(light)
    return "#{intern_helper_ampel_or_sila(light)} #{light.match(/\d{1,3}/)}"
  end

  # Extracts ampel
  def intern_helper_ampel_or_sila(light)
    return light.match(/ampel/i).to_s.capitalize if light.match?(/ampel/i)
    return light.match(/euroskilt/i).to_s.capitalize if light.match?(/euroskilt/i)
  end

  # Gets Sila lights from portal and organises them into an nested array
  def helper_get_lights

    # Log into the portal
    mechanize = Mechanize.new
    page_full = mechanize.get('https://www.sila-signalbau.de/Login_Ampelueberwachung.htm?ActiveID=1226')
    form = page_full.form('form1')
    form['ctl01$tbUser'] = 'Drammen08'
    form['ctl01$tbPassword'] = 'Avdeling08'
    page = form.click_button

    # Search the page for all lights
    temp_list = page.search('tr td').map{ |x | x.text }
    lights_count = (temp_list.count / 11) - 1

    # Create an nested array for each light
    lights = Array.new

    # Add each light into appropriate array container
    temp_count = 1
    lights_count.times do
      lights << temp_list[(temp_count * 11)..((temp_count*11)+1)]
      temp_count += 1
    end

    return lights
  end

  # Create lights that are not there
  def helper_create_lights_if_not_there(light)
    sila_id = helper_sila_or_ampel_id(light[0][0])
    ampel_id = helper_sila_or_ampel_id(light[0][1])

    # Check if light exists, else create it
    Sila.where(sila_id: sila_id, ampel_id: ampel_id).first_or_create
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sila lights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="sidebar">
      <%= render 'layouts/partials/sidebar' %>
    </div>
    <div class="content">
      <%= render 'layouts/partials/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<div class="flash">
  <% flash.each do |type, msg| %>
    <div class="<%= helper_flash_type(type) %>">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/partials/_sidebar.html.erb
<div class="sidebar-title">
  <h1>Sila lights</h1>
</div>
<div class="sidebar-menu">
  <%= link_to "All ligths", root_path %>
  <% @silas.each do | sila | %>
    <%= link_to "#{ sila.sila_id }", "#", class: "small" %>
  <% end %>
</div>

app/views/silas/_form.html.erb
<%= form_with(model: sila, local: true) do |form| %>
  <% if sila.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sila.errors.count, "error") %> prohibited this sila from being saved:</h2>

      <ul>
        <% sila.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sila-id %>
    <%= form.text_field :sila-id %>
  </div>

  <div class="field">
    <%= form.label :ampel-id %>
    <%= form.text_field :ampel-id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/silas/edit.html.erb
<h1>Editing Sila</h1>

<%= render 'form', sila: @sila %>

<%= link_to 'Show', @sila %> |
<%= link_to 'Back', silas_path %>

app/views/silas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sila lights</h1>
<div>
  <p>There are <%= @silas.count %> lights registered, and we have found <%= @lights_count %> lights on the portal.</p>
</div>

<table class="table mt-3">
  <thead>
    <tr class="first">
      <th class="id">#</th>
      <th>Sila ID</th>
      <th>Ampel ID</th>
      <th>Light type</th>
      <th>Error code</th>
      <th>Last seen</th>
      <th>Location</th>
      <th>Online</th>
      <th class="last">Battery</th>
      <th colspan="3" class="last"></th>
    </tr>
  </thead>

  <tbody>
    <% if @silas.empty? %>
      <tr><td>No lights found</td></tr>
    <% else %>
      <% @silas.each do |light| %>
        <tr class="">
          <td><%= light.id %></td>
          <td><%= helper_sila_or_ampel_id(light.sila_id) %></td>
          <td><%= helper_sila_or_ampel_id(light.ampel_id) %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="last"></td>
          <td>
            <div class="btn-group">
              <%= link_to "Inspect", "#", class: "btn btn-main pl-2 pr-2 pt-1 pd-1" %>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/silas/new.html.erb
<h1>New Sila</h1>

<%= render 'form', sila: @sila %>

<%= link_to 'Back', silas_path %>

app/views/silas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sila-id:</strong>
  <%= @sila.sila-id %>
</p>

<p>
  <strong>Ampel-id:</strong>
  <%= @sila.ampel-id %>
</p>

<%= link_to 'Edit', edit_sila_path(@sila) %> |
<%= link_to 'Back', silas_path %>